ARGS = \
  SUFFIX='-quad' \
  FC='xlf' \
  FFLAGS_QUAD='-qautodbl=dbl -WF,-DKIND=2' \
  CC='cc -DKIND=2'

default all: force
	$(MAKE) $(ARGS) default

install: force
	$(MAKE) $(ARGS) install

clean: force
	$(MAKE) $(ARGS) clean

force:

