SUFFIX = -quad
FC-quad = $(FC)
FFLAGS-quad = -r16 -DQUAD=1 -DKIND=2 -DDBLE=QEXT -DDIMAG=QIMAG -DDCONJG=QCONJG -DDCMPLX=QCMPLX
CFLAGS-quad = -DKIND=2
INCLUDE-quad = $(BLD)/looptools.h

include makefile

