ARGS = \
  SUFFIX='-quad' \
  FC='ifort' \
  FFLAGS='-O3 -fpe0 -g -r16 -DQUAD -DKIND=2 -DDBLE=QEXT -DDIMAG=QIMAG -DDCONJG=QCONJG -DDCMPLX=QCMPLX' \
  CC='cc -DKIND=2'

default all: force
	$(MAKE) $(ARGS) default

install: force
	$(MAKE) $(ARGS) install

clean: force
	$(MAKE) $(ARGS) clean

force:

