#! /bin/sh

set -o pipefail

sdkpath()
{
  "$@" << \_EOF_ 2> /dev/null | tail -1
	WriteString["stdout", "\n" <>
	  ToFileName[{$TopDirectory, "AddOns", "MathLink",
	    "DeveloperKit", $SystemID, "CompilerAdditions"}]]; Exit[]
_EOF_
}


sdkpath math
echo $?

sdkpath abc
echo $?

