#if 0
This file was generated by mkexternalsh on Wed Sep 19 09:55:13 CEST 2012.
Do not edit.
#endif

#if NOUNDERSCORE

#define cachecopy ljcachecopy
#define cacheindex ljcacheindex

#else

#define cachecopy_ ljcachecopy_
#define cacheindex_ ljcacheindex_

#endif
